export type CommandCapability = "offline" | "online" | "dual";

export const COMMAND_CAPABILITIES = {
  init: "offline",
  "profile add": "offline",
  "bot add": "offline",
  "bot authorize": "offline",
  "skills init": "offline",
  restore: "offline",
  pair: "online",
  "identity workspace set": "online",
  "group authorize": "online",
  "group authorize-code": "online",
  "conversation list": "online",
  "schedule add": "online",
  "schedule list": "online",
  "schedule update": "online",
  "schedule pause": "online",
  "schedule resume": "online",
  "schedule remove": "online",
  "schedule run": "online",
  "schedule reset-context": "online",
  "schedule history": "online",
  doctor: "dual",
  status: "dual",
  "identity list": "dual",
  "group list": "dual",
  "memory status": "dual",
  "memory list": "dual",
  "memory show": "dual",
  "skills list": "dual",
  "skills validate": "dual",
  backup: "dual",
} as const satisfies Record<string, CommandCapability>;

export type CommandName = keyof typeof COMMAND_CAPABILITIES;
