import type { ErrorDefinition } from "./types.js";

export const ERROR_DEFINITIONS = {
  CONFIG_FILE_UNREADABLE: {
    domain: "config",
    kind: "validation",
    messageKey: "error.config_file_unreadable.message",
    actionKey: "error.config_file_unreadable.action",
    retry: { strategy: "after_user_action", replay: "safe" },
  },
  CONFIG_FILE_INVALID: {
    domain: "config",
    kind: "validation",
    messageKey: "error.config_file_invalid.message",
    actionKey: "error.config_file_invalid.action",
    retry: { strategy: "after_user_action", replay: "safe" },
  },
  CONFIG_WORKSPACE_INVALID: {
    domain: "config",
    kind: "validation",
    messageKey: "error.config_workspace_invalid.message",
    actionKey: "error.config_workspace_invalid.action",
    retry: { strategy: "after_user_action", replay: "safe" },
  },
  CLI_USAGE_INVALID: {
    domain: "config",
    kind: "validation",
    messageKey: "error.cli_usage_invalid.message",
    actionKey: "error.cli_usage_invalid.action",
    retry: { strategy: "none", replay: "safe" },
  },
  LANGUAGE_UNSUPPORTED: {
    domain: "config",
    kind: "validation",
    messageKey: "error.language_unsupported.message",
    actionKey: "error.language_unsupported.action",
    retry: { strategy: "none", replay: "safe" },
  },
  RUNTIME_NODE_UNSUPPORTED: {
    domain: "runtime",
    kind: "compatibility",
    messageKey: "error.runtime_node_unsupported.message",
    actionKey: "error.runtime_node_unsupported.action",
    retry: { strategy: "after_user_action", replay: "safe" },
  },
  RUNTIME_SERVICE_NOT_RUNNING: {
    domain: "runtime",
    kind: "not_found",
    messageKey: "error.runtime_service_not_running.message",
    actionKey: "error.runtime_service_not_running.action",
    retry: { strategy: "after_user_action", replay: "safe" },
  },
  RUNTIME_SERVICE_MUST_STOP: {
    domain: "runtime",
    kind: "conflict",
    messageKey: "error.runtime_service_must_stop.message",
    actionKey: "error.runtime_service_must_stop.action",
    retry: { strategy: "after_user_action", replay: "safe" },
  },
  RUNTIME_CONTROL_UNREACHABLE: {
    domain: "runtime",
    kind: "transient",
    messageKey: "error.runtime_control_unreachable.message",
    actionKey: "error.runtime_control_unreachable.action",
    retry: { strategy: "backoff", replay: "safe" },
  },
  RUNTIME_CONTROL_PROTOCOL_UNSUPPORTED: {
    domain: "runtime",
    kind: "compatibility",
    messageKey: "error.runtime_control_protocol_unsupported.message",
    actionKey: "error.runtime_control_protocol_unsupported.action",
    retry: { strategy: "after_user_action", replay: "safe" },
  },
  RUNTIME_INSTANCE_CONFLICT: {
    domain: "runtime",
    kind: "conflict",
    messageKey: "error.runtime_instance_conflict.message",
    actionKey: "error.runtime_instance_conflict.action",
    retry: { strategy: "after_user_action", replay: "safe" },
  },
  RUNTIME_INSTANCE_MISMATCH: {
    domain: "runtime",
    kind: "conflict",
    messageKey: "error.runtime_instance_mismatch.message",
    actionKey: "error.runtime_instance_mismatch.action",
    retry: { strategy: "after_user_action", replay: "safe" },
  },
  STORAGE_UNAVAILABLE: {
    domain: "storage",
    kind: "internal",
    messageKey: "error.storage_unavailable.message",
    actionKey: "error.storage_unavailable.action",
    retry: { strategy: "after_user_action", replay: "unknown" },
  },
  STORAGE_MIGRATION_FAILED: {
    domain: "storage",
    kind: "internal",
    messageKey: "error.storage_migration_failed.message",
    actionKey: "error.storage_migration_failed.action",
    retry: { strategy: "after_user_action", replay: "unknown" },
  },
  ADAPTER_AUTH_REQUIRED: {
    domain: "adapter",
    kind: "authentication",
    messageKey: "error.adapter_auth_required.message",
    actionKey: "error.adapter_auth_required.action",
    retry: { strategy: "after_user_action", replay: "safe" },
  },
  ADAPTER_PERMISSION_DENIED: {
    domain: "adapter",
    kind: "authorization",
    messageKey: "error.adapter_permission_denied.message",
    actionKey: "error.adapter_permission_denied.action",
    retry: { strategy: "after_user_action", replay: "safe" },
  },
  ADAPTER_SESSION_INVALID: {
    domain: "adapter",
    kind: "authentication",
    messageKey: "error.adapter_session_invalid.message",
    actionKey: "error.adapter_session_invalid.action",
    retry: { strategy: "after_user_action", replay: "safe" },
  },
  ADAPTER_RATE_LIMITED: {
    domain: "adapter",
    kind: "rate_limit",
    messageKey: "error.adapter_rate_limited.message",
    actionKey: "error.adapter_rate_limited.action",
    retry: { strategy: "backoff", replay: "safe" },
  },
  ADAPTER_REQUEST_TIMEOUT: {
    domain: "adapter",
    kind: "timeout",
    messageKey: "error.adapter_request_timeout.message",
    actionKey: "error.adapter_request_timeout.action",
    retry: { strategy: "backoff", replay: "safe" },
  },
  ADAPTER_SERVICE_UNAVAILABLE: {
    domain: "adapter",
    kind: "transient",
    messageKey: "error.adapter_service_unavailable.message",
    actionKey: "error.adapter_service_unavailable.action",
    retry: { strategy: "backoff", replay: "safe" },
  },
  ADAPTER_REQUEST_REJECTED: {
    domain: "adapter",
    kind: "validation",
    messageKey: "error.adapter_request_rejected.message",
    actionKey: "error.adapter_request_rejected.action",
    retry: { strategy: "none", replay: "safe" },
  },
  ADAPTER_REPLY_CONTEXT_INVALID: {
    domain: "adapter",
    kind: "conflict",
    messageKey: "error.adapter_reply_context_invalid.message",
    actionKey: "error.adapter_reply_context_invalid.action",
    retry: { strategy: "none", replay: "safe" },
  },
  ADAPTER_COMPATIBILITY_ERROR: {
    domain: "adapter",
    kind: "compatibility",
    messageKey: "error.adapter_compatibility_error.message",
    actionKey: "error.adapter_compatibility_error.action",
    retry: { strategy: "none", replay: "safe" },
  },
  ADAPTER_CONNECTION_FAILED: {
    domain: "adapter",
    kind: "transient",
    messageKey: "error.adapter_connection_failed.message",
    actionKey: "error.adapter_connection_failed.action",
    retry: { strategy: "backoff", replay: "safe" },
  },
  AGENT_AUTH_REQUIRED: {
    domain: "driver",
    kind: "authentication",
    messageKey: "error.agent_auth_required.message",
    actionKey: "error.agent_auth_required.action",
    retry: { strategy: "after_user_action", replay: "safe" },
  },
  AGENT_VERSION_UNSUPPORTED: {
    domain: "driver",
    kind: "compatibility",
    messageKey: "error.agent_version_unsupported.message",
    actionKey: "error.agent_version_unsupported.action",
    retry: { strategy: "after_user_action", replay: "safe" },
  },
  AGENT_UNAVAILABLE: {
    domain: "driver",
    kind: "transient",
    messageKey: "error.agent_unavailable.message",
    actionKey: "error.agent_unavailable.action",
    retry: { strategy: "backoff", replay: "safe" },
  },
  AGENT_TURN_START_FAILED: {
    domain: "driver",
    kind: "transient",
    messageKey: "error.agent_turn_start_failed.message",
    actionKey: "error.agent_turn_start_failed.action",
    retry: { strategy: "backoff", replay: "safe" },
  },
  AGENT_TURN_FAILED: {
    domain: "driver",
    kind: "internal",
    messageKey: "error.agent_turn_failed.message",
    actionKey: "error.agent_turn_failed.action",
    retry: { strategy: "none", replay: "unknown" },
  },
  AGENT_SESSION_MISMATCH: {
    domain: "driver",
    kind: "conflict",
    messageKey: "error.agent_session_mismatch.message",
    actionKey: "error.agent_session_mismatch.action",
    retry: { strategy: "after_user_action", replay: "safe" },
  },
  DRIVER_PROTOCOL_INCOMPLETE: {
    domain: "driver",
    kind: "internal",
    messageKey: "error.driver_protocol_incomplete.message",
    actionKey: "error.driver_protocol_incomplete.action",
    retry: { strategy: "backoff", replay: "safe" },
  },
  PROFILE_OR_DRIVER_MISSING: {
    domain: "task",
    kind: "not_found",
    messageKey: "error.profile_or_driver_missing.message",
    actionKey: "error.profile_or_driver_missing.action",
    retry: { strategy: "after_user_action", replay: "safe" },
  },
  TASK_EXECUTION_FAILED: {
    domain: "task",
    kind: "internal",
    messageKey: "error.task_execution_failed.message",
    actionKey: "error.task_execution_failed.action",
    retry: { strategy: "none", replay: "unknown" },
  },
  TASK_RETRY_EXHAUSTED: {
    domain: "task",
    kind: "transient",
    messageKey: "error.task_retry_exhausted.message",
    actionKey: "error.task_retry_exhausted.action",
    retry: { strategy: "none", replay: "safe" },
  },
  TASK_UNSAFE_REPLAY: {
    domain: "task",
    kind: "conflict",
    messageKey: "error.task_unsafe_replay.message",
    actionKey: "error.task_unsafe_replay.action",
    retry: { strategy: "after_user_action", replay: "unsafe" },
  },
  PROCESS_RESTART_RECOVERY: {
    domain: "task",
    kind: "transient",
    messageKey: "error.process_restart_recovery.message",
    actionKey: "error.process_restart_recovery.action",
    retry: { strategy: "backoff", replay: "safe" },
  },
  OUTBOUND_RATE_LIMITED: {
    domain: "outbound",
    kind: "rate_limit",
    messageKey: "error.outbound_rate_limited.message",
    actionKey: "error.outbound_rate_limited.action",
    retry: { strategy: "backoff", replay: "safe" },
  },
  OUTBOUND_CONTEXT_EXPIRED: {
    domain: "outbound",
    kind: "conflict",
    messageKey: "error.outbound_context_expired.message",
    actionKey: "error.outbound_context_expired.action",
    retry: { strategy: "none", replay: "safe" },
  },
  OUTBOUND_PLATFORM_REJECTED: {
    domain: "outbound",
    kind: "validation",
    messageKey: "error.outbound_platform_rejected.message",
    actionKey: "error.outbound_platform_rejected.action",
    retry: { strategy: "none", replay: "safe" },
  },
  OUTBOUND_SEND_FAILED: {
    domain: "outbound",
    kind: "transient",
    messageKey: "error.outbound_send_failed.message",
    actionKey: "error.outbound_send_failed.action",
    retry: { strategy: "backoff", replay: "safe" },
  },
  APPROVAL_NOT_FOUND: {
    domain: "approval",
    kind: "not_found",
    messageKey: "error.approval_not_found.message",
    actionKey: "error.approval_not_found.action",
    retry: { strategy: "none", replay: "safe" },
  },
  APPROVAL_FORBIDDEN: {
    domain: "approval",
    kind: "authorization",
    messageKey: "error.approval_forbidden.message",
    actionKey: "error.approval_forbidden.action",
    retry: { strategy: "none", replay: "safe" },
  },
  APPROVAL_EXPIRED: {
    domain: "approval",
    kind: "conflict",
    messageKey: "error.approval_expired.message",
    actionKey: "error.approval_expired.action",
    retry: { strategy: "none", replay: "safe" },
  },
  IDENTITY_OPERATION_REJECTED: {
    domain: "identity",
    kind: "authorization",
    messageKey: "error.identity_operation_rejected.message",
    actionKey: "error.identity_operation_rejected.action",
    retry: { strategy: "none", replay: "safe" },
  },
  MEMORY_OPERATION_REJECTED: {
    domain: "memory",
    kind: "authorization",
    messageKey: "error.memory_operation_rejected.message",
    actionKey: "error.memory_operation_rejected.action",
    retry: { strategy: "none", replay: "safe" },
  },
  MEMORY_CURATION_FAILED: {
    domain: "memory",
    kind: "transient",
    messageKey: "error.memory_curation_failed.message",
    actionKey: "error.memory_curation_failed.action",
    retry: { strategy: "backoff", replay: "safe" },
  },
  LEGACY_RECORDED_ERROR: {
    domain: "internal",
    kind: "internal",
    messageKey: "error.legacy_recorded_error.message",
    actionKey: "error.legacy_recorded_error.action",
    retry: { strategy: "none", replay: "unknown" },
  },
  INTERNAL_UNEXPECTED_ERROR: {
    domain: "internal",
    kind: "internal",
    messageKey: "error.internal_unexpected_error.message",
    actionKey: "error.internal_unexpected_error.action",
    retry: { strategy: "none", replay: "unknown" },
  },
} as const satisfies Record<string, ErrorDefinition>;

export type ErrorCode = keyof typeof ERROR_DEFINITIONS;
